### ISSUE TITLE
Comment on tutorial_read_spatial

### ISSUE THREAD

**Issue by jwrth** [theislab/squidpy_notebooks#47]
@giovp So here my comment on the tutorial.

First, I think it's a great idea to do such a general tutorial! It helps a lot to understand the general structure of the data and will make it a lot easier to fit in own data. Really nice job!

I tried to run the tutorial in a notebook and came across following error when trying to plot the dummy adata:

![grafik](https://user-images.githubusercontent.com/76480183/107799007-2e3bf700-6d5d-11eb-9f1d-524f69ac4cfb.png)

It looks for me like the function is searching for the `'spatial'` coordinates in `adata.uns['spatial']` instead of `adata.obsm['spatial']`.

And when I added the spatial coordinates to `adata.uns['spatial']` it says `'numpy.ndarray' object has no attribute 'keys'`. Why does `sc.pl.spatial()` expect a dictionary in `adata.uns['spatial']`?

When this works I'll try to fit in my Dbit-seq data. Really excited to apply all the Squidpy functions to it!

**Comment by jwrth** [comment]
Ah yes that explains it 😄 Now it's working. Very nice! Only in the very last line the error `AttributeError: 'ImageContainer' object has no attribute 'show'` appears.

Beside that: Would it be possible to make not only the spot size but also the spot shape of the spatial plots customizable? For Dbit-seq I would need squares instead of circles.

Didn't have time to test it on my data yet but I'll let you know as soon as I did.

**Comment by giovp** [comment]
> Ah yes that explains it 😄 Now it's working. Very nice! Only in the very last line the error AttributeError: 'ImageContainer' object has no attribute 'show' appears.

mmh this is weird... can you try to re clone the latest version of the repo and re install it with `pip install squidpy[dev]` ?

> Beside that: Would it be possible to make not only the spot size but also the spot shape of the spatial plots customizable? For Dbit-seq I would need squares instead of circles.

this is a good point, and not, it's not supported now but should be too difficult to be added. I'll make a new issue in scanpy and tag youthere.

**Comment by michalk8** [comment]
> Beside that: Would it be possible to make not only the spot size but also the spot shape of the spatial plots customizable? For Dbit-seq I would need squares instead of circles.

> this is a good point, and not, it's not supported now but should be too difficult to be added. I'll make a new issue in scanpy and tag youthere.

Think we can already support this in `squidpy.im.ImageContainer.interactive` - napari has a square glyph (among many others), but selecting glyphs is disabled because you could also have an asterisk, etc.

**Comment by michalk8** [comment]
I believe this can be closed (feel free to reopen if I'm wrong).
