### ISSUE TITLE
imctutorial squidpy environment install fail

### ISSUE THREAD

**Issue by mezwick** [theislab/squidpy_notebooks#55]
Hi,

I have tried to create a conda environment with the environment.yml file at
https://github.com/theislab/squidpy_notebooks/blob/master/environment.yml

As per the IMC tutorial instructions https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_imc.html

However, I get the following error and cannot create the environment
```
ERROR: Could not find a version that satisfies the requirement rasterio>=1.1.8 (from squidpy)
ERROR: No matching distribution found for rasterio>=1.1.8

failed

CondaEnvException: Pip failed
```

**Comment by michalk8** [comment]
Hi @mezwick ,

could it be because we had wrongly specified the conda installation command (was: `conda create -f ...`, should be `conda env create -f ...`, see #56 .
I've also tried to create the environment, didn't encounter the issue (my conda version is `4.9.2`, pip version inside is `21.0.1`).

**Comment by mezwick** [comment]
Hi @michalk8 

It seems to be an issue to do with `pip install rasterio` that has popped up in a few places...
https://github.com/azavea/raster-vision/issues/518
https://github.com/azavea/raster-vision/issues/598

Will see if i can work around

**Comment by mezwick** [comment]
The issue installing Squidpy that arises because rasterio and GDAL fail to install can be circumvented by manually downloading rasterio and GDAL files, then pip installing them locally. This answer was provided by @byander https://github.com/mapbox/rasterio/issues/1963#issuecomment-672262445

rasterio and GDAL binaries (unofficial) can be downloaded from here
https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by michalk8** [comment]
thank for the info @mezwick 
we're considering using `dask_image` in https://github.com/theislab/squidpy/issues/296 , so in the future, there'd be no rasterio dependency
