### ISSUE TITLE
tangram 0.3.0 removes mapping_optimizer.MapperConstrained

### ISSUE THREAD

**Issue by asabjorklund** [theislab/squidpy_notebooks#58]
Thank you for this great package and helpful tutorials! 

I am trying to reproduce the Tangram tutorial but found that the class `tg.mapping_optimizer.MapperConstrained` is not available anymore. Turns out that in the new release tangram==0.3.0 they have removed that class. However, if I revert to tangram==0.1.3 it works fine to run the tutorial. 

Just thought you should know so you can specify which version of Tangram to use or update the tutorial.

Keep up the great work!
/Åsa

**Comment by giovp** [comment]
HI @asabjorklund ,

thank you for the interest in Squidpy! Indeed great chatch, we are actually working toward providing a wrapper for Tangram (see: https://github.com/theislab/squidpy/pull/316 ). We should however pin the version in `environment.yml`/notebooks in the meantime. Will try to do it asap. 
Thanks again!

**Comment by giovp** [comment]
@asabjorklund you should now be able to use latest squidpy and tangram without any issue (see dev branch for notebook just pushed), closing this, feel free to reopen if needed
