### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy_notebooks#59]
Because `sq.gr.moran` is missing in:

- [ ] tutorial_visium_hne.py
- [ ] compute_moran.py

@giovp ~~since Moran's now in scanpy, should we keep the 2nd example? I'd say yes.~~
2nd question, since we're restructuring the main repo (Z-dim, etc.), I'd suggest merging PRs there to dev, not to master.
That way, we can have stable/latest docs + notebooks can get broken only after making a new release + forgetting to change them.
Happy for other alternatives/suggestions.

**Comment by giovp** [comment]
hey michal, sorry for late reply

> 2nd question, since we're restructuring the main repo (Z-dim, etc.), I'd suggest merging PRs there to dev, not to master.
That way, we can have stable/latest docs + notebooks can get broken only after making a new release + forgetting to change them.

I agree, saw you started already. Yes let's then keep master clean and only update when new version, and work on dev
