### ISSUE TITLE
cell type visualization with segmentation mask

### ISSUE THREAD

**Issue by YubinXie** [theislab/squidpy_notebooks#61]
Hi Squidpy team,

It is great to see you are developing platform for spatial analysis. I did not see an example of plotting cell in an image with its real segmentation mask. Will it be on squidpy?

**Comment by michalk8** [comment]
There's this [tutorial](https://squidpy.readthedocs.io/en/stable/auto_examples/image/compute_segment_fluo.html), or using `segmentation_layer` argument in [here](https://squidpy.readthedocs.io/en/stable/classes/squidpy.im.ImageContainer.show.html#squidpy.im.ImageContainer.show), implemented in https://github.com/theislab/squidpy/issues/336.
Alternatively, it's always possible to visualize the segmentation interactively with `napari` using `ImageContainer.interactive`.
Think this has been solved, feel free to (re-)open if there are any problems/other quetions arise.
