### ISSUE TITLE
update tutorials.rst in squidpy

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy_notebooks#71]
in #64 I had a separation of dataset-analysis tutorials and advanced Squidpy tutorials (Napari, reading spatial data, image container). Could copy this new version to squidpy to have this separation in the "lastest" docs?

**Comment by michalk8** [comment]
closed via https://github.com/theislab/squidpy_notebooks/pull/73 and https://github.com/theislab/squidpy_notebooks/commit/f728d6c8de6a8ddbda37469fab00535d9651a591.
