### ISSUE TITLE
scrna-sea and mFISH example

### ISSUE THREAD

**Issue by FADHLyemen** [theislab/squidpy_notebooks#79]
Hi,
Could you example with scrna-seq from 10x and image from same tissue?

**Comment by giovp** [comment]
hello!
there are several examples regarding this settings you just mentioned: 
https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_visium_fluo.html
https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_visium_hne.html

let me know if they are useful!

**Comment by FADHLyemen** [comment]
do have example not using Visium?

**Comment by giovp** [comment]
many, check tutorials and examples here: 
https://squidpy.readthedocs.io/en/latest/examples.html
https://squidpy.readthedocs.io/en/latest/tutorials.html

**Comment by giovp** [comment]
hello @FADHLyemen was the sugested tutorials useful?

**Comment by giovp** [comment]
I'm gonna close this, feel free to reopen if not resolved
